# Generated by Django 6.0.1 on 2026-01-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=200)),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('month_vwap_low', models.FloatField()),
                ('month_vwap_high', models.FloatField()),
                ('year_vwap_low', models.FloatField()),
                ('year_vwap_high', models.FloatField()),
                ('ma_9', models.FloatField()),
                ('ma_21', models.FloatField()),
                ('pivot', models.FloatField()),
                ('pivot_high_1', models.FloatField()),
                ('pivot_high_2', models.FloatField()),
                ('pivot_high_3', models.FloatField()),
                ('pivot_low_1', models.FloatField()),
                ('pivot_low_2', models.FloatField()),
                ('pivot_low_3', models.FloatField()),
            ],
        ),
    ]
