# Generated by Django 6.0.1 on 2026-01-22 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equity',
            name='close',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='high',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='low',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='ma_21',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='ma_9',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='month_vwap_high',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='month_vwap_low',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='open',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='pivot',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='pivot_high_1',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='pivot_high_2',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='pivot_high_3',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='pivot_low_1',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='pivot_low_2',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='pivot_low_3',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='year_vwap_high',
        ),
        migrations.RemoveField(
            model_name='equity',
            name='year_vwap_low',
        ),
        migrations.AddField(
            model_name='equity',
            name='description',
            field=models.CharField(default='No Description', max_length=1000),
        ),
        migrations.AlterField(
            model_name='equity',
            name='ticker',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='DailyCandles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.FloatField()),
                ('close', models.FloatField()),
                ('high', models.FloatField()),
                ('low', models.FloatField()),
                ('month_vwap_low', models.FloatField()),
                ('month_vwap_high', models.FloatField()),
                ('year_vwap_low', models.FloatField()),
                ('year_vwap_high', models.FloatField()),
                ('ma_9', models.FloatField()),
                ('ma_21', models.FloatField()),
                ('pivot', models.FloatField()),
                ('pivot_high_1', models.FloatField()),
                ('pivot_high_2', models.FloatField()),
                ('pivot_high_3', models.FloatField()),
                ('pivot_low_1', models.FloatField()),
                ('pivot_low_2', models.FloatField()),
                ('pivot_low_3', models.FloatField()),
                ('equity_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equities.equity')),
            ],
        ),
    ]
