# Generated by Django 6.0.1 on 2026-01-22 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0002_remove_equity_close_remove_equity_high_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equity',
            name='description',
            field=models.TextField(default='No Description', max_length=1000),
        ),
    ]
