# Generated by Django 6.0.1 on 2026-01-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equities', '0003_alter_equity_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='equity',
            name='name',
            field=models.CharField(default='Ticker', max_length=50),
        ),
        migrations.DeleteModel(
            name='DailyCandles',
        ),
    ]
